name: Deploy
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: eiei114/shiritoridenoapp:${{ github.sha }}
          dockerfile: Dockerfile
      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          cmd: ["run", "--allow-net", "--allow-read", "server.js"]
          project: "eiei114-deno-shiritori"
          image: "eiei114/shiritoridenoapp:${{ github.sha }}"